### ISSUE TITLE
Include softwarerepourl and ClientIdentifier in pkg-file / payload

### ISSUE THREAD

**Issue by somethingavailable** [lifeunexpected/Scripts#1]
This is the first script that has successfully passed apples gatekeeper trying to build a notarized version of Munki-installert. Thanks.

I wonder if it is possible to add a payload script in this package that is created with this script so the ClientIdentifier and SoftwareRepoURL is fixed. 
Ex:
#!/bin/sh
sudo defaults write /Library/Preferences/ManagedInstalls SoftwareRepoURL "http://munki.organization.com/munki_repo"
sudo defaults write /Library/Preferences/ManagedInstalls ClientIdentifier Group1_employees

**Comment by lifeunexpected** [comment]
hey this was added by Greg for the original make_munki_mpkg.sh so you could probably try the command below and it should get you what you want. I havent tried it yet but i need the the same as you ask about so i will try it later today.

https://github.com/munki/munki/blob/main/code/tools/make_munki_mpkg.sh#L54
-c plist    Build a configuration package using the preferences defined in a

sudo $MUNKIROOT/code/tools/make_munki_mpkg.sh -i "$BUNDLE_ID" -S "$DevApp" -s "$DevInst" -c "Path/to/plist/file"
